---
# tasks file for zabbix-agent

- name: Download Zabbix release deb
  ansible.builtin.get_url:
    url: "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb"
    dest: "/tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb"

- name: Install Zabbix release deb
  ansible.builtin.apt:
    deb: "/tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb"

- name: Update the package list and install Zabbix agent
  ansible.builtin.apt:
    update_cache: yes
    name: zabbix-agent
    state: present

- name: Configure Zabbix Agent
  ansible.builtin.template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent

- name: Ensure Zabbix Agent is running and enabled
  ansible.builtin.systemd:
    name: zabbix-agent
    state: restarted
    enabled: true

- name: Authenticate to Zabbix and get auth token
  uri:
    url: "{{ zabbix_url }}/api_jsonrpc.php"
    method: POST
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "user.login"
      params:
        username: "{{ zabbix_user }}"
        password: "{{ zabbix_password }}"
      id: 1
    headers:
      Content-Type: "application/json"
    validate_certs: no 
  register: login_response

- name: Debug login response
  debug:
    var: login_response.json

- name: Register host in Zabbix
  uri:
    url: "{{ zabbix_url }}/api_jsonrpc.php"
    method: POST
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "host.create"
      params:
        host: "{{ inventory_hostname }}"
        interfaces: [
          {
            "type": 1,
            "main": 1,
            "useip": 1,
            "ip": "{{ ansible_default_ipv4.address }}",
            "dns": "",
            "port": "10050"
          }
        ]
        groups: [{"groupid": "2"}]  
        templates: [{"templateid": "10001"}] 
        inventory_mode: 0
      auth: "{{ login_response.json.result }}"
      id: 2
    headers:
      Content-Type: "application/json"
  register: host_creation_response

- name: Check host creation result
  debug:
    var: host_creation_response.json
